#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SharedCountdown.Resource", IsApplication=true)]

namespace SharedCountdown
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int NameTextView = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int NotesTextView = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int btnDateSelect = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int lblDate = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int lblName = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int lstCountdowns = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int menu_add_countdown = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int menu_delete_countdown = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int menu_save_countdown = 2131099659;
			
			// aapt resource value: 0x7f060000
			public const int relativeLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int root = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int txtDate = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int txtName = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int txtNotes = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CountdownDetail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CountdownListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int HomeScreen = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int menu_detailsscreen = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int menu_homescreen = 2131034113;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
